/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.PandaUnitySimulation
{
    public class BoundingBox : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "panda_unity_simulation/BoundingBox";

        public Header header;
        public string name;
        public Pose pose;
        public Vector3 dims;

        public BoundingBox()
        {
            this.header = new Header();
            this.name = "";
            this.pose = new Pose();
            this.dims = new Vector3();
        }

        public BoundingBox(Header header, string name, Pose pose, Vector3 dims)
        {
            this.header = header;
            this.name = name;
            this.pose = pose;
            this.dims = dims;
        }
    }
}
