/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.MoveBase
{
    public class MoveBaseFeedback : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "move_base_msgs/MoveBaseFeedback";

        //  MoveBase feedback
        public PoseStamped base_position;

        public MoveBaseFeedback()
        {
            this.base_position = new PoseStamped();
        }

        public MoveBaseFeedback(PoseStamped base_position)
        {
            this.base_position = base_position;
        }
    }
}
