/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Actionlib;

namespace RosSharp.RosBridgeClient.MessageTypes.MoveBase
{
    public class MoveBaseActionFeedback : ActionFeedback<MoveBaseFeedback>
    {
        [JsonIgnore]
        public const string RosMessageName = "move_base_msgs/MoveBaseActionFeedback";

        public MoveBaseActionFeedback() : base()
        {
            this.feedback = new MoveBaseFeedback();
        }

        public MoveBaseActionFeedback(Header header, GoalStatus status, MoveBaseFeedback feedback) : base(header, status)
        {
            this.feedback = feedback;
        }
    }
}
