/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.MoveBase
{
    public class MoveBaseResult : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "move_base_msgs/MoveBaseResult";

        //  Move base result - no result

        public MoveBaseResult()
        {
        }
    }
}
