/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.PandaUnitySimulation
{
    public class ConfirmPathMoveitResult : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "panda_unity_simulation/ConfirmPathMoveitResult";

        // Result definition
        public bool confirmationResult;

        public ConfirmPathMoveitResult()
        {
            this.confirmationResult = false;
        }

        public ConfirmPathMoveitResult(bool confirmationResult)
        {
            this.confirmationResult = confirmationResult;
        }
    }
}
