/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Actionlib;

namespace RosSharp.RosBridgeClient.MessageTypes.PandaUnitySimulation
{
    public class ConfirmPathMoveitActionResult : ActionResult<ConfirmPathMoveitResult>
    {
        [JsonIgnore]
        public const string RosMessageName = "panda_unity_simulation/ConfirmPathMoveitActionResult";

        public ConfirmPathMoveitActionResult() : base()
        {
            this.result = new ConfirmPathMoveitResult();
        }

        public ConfirmPathMoveitActionResult(Header header, GoalStatus status, ConfirmPathMoveitResult result) : base(header, status)
        {
            this.result = result;
        }
    }
}
