/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.PandaUnitySimulation
{
    public class ConfirmPathMoveitGoal : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "panda_unity_simulation/ConfirmPathMoveitGoal";

        // Goal definition
        public bool confirmation;

        public ConfirmPathMoveitGoal()
        {
            this.confirmation = false;
        }

        public ConfirmPathMoveitGoal(bool confirmation)
        {
            this.confirmation = confirmation;
        }
    }
}
