/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

using RosSharp.RosBridgeClient.MessageTypes.PandaUnitySimulation;

namespace RosSharp.RosBridgeClient.MessageTypes.PandaUnitySimulation
{
    public class RegisterCollisionObjectsGoal : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "panda_unity_simulation/RegisterCollisionObjectsGoal";

        //  Request
        //  An array of bounding boxes to add to the scene
        public BoundingBox[] boundingBoxes;
        //  An array of meshes from the HL spatial mapping to add to the scene
        public SpatialMappingMesh[] spatialMappingMeshes;

        public RegisterCollisionObjectsGoal()
        {
            this.boundingBoxes = new BoundingBox[0];
            this.spatialMappingMeshes = new SpatialMappingMesh[0];
        }

        public RegisterCollisionObjectsGoal(BoundingBox[] boundingBoxes, SpatialMappingMesh[] spatialMappingMeshes)
        {
            this.boundingBoxes = boundingBoxes;
            this.spatialMappingMeshes = spatialMappingMeshes;
        }
    }
}
