/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.Moveit
{
    public class PoseMoveitGoal : Message
    {
        public const string RosMessageName = "Moveit/PoseMoveitGoal";

        // Goal definition
        public Pose targetPose { get; set; }

        public PoseMoveitGoal()
        {
            this.targetPose = new Pose();
        }

        public PoseMoveitGoal(Pose targetPose)
        {
            this.targetPose = targetPose;
        }
    }
}
