/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Moveit
{
    public class PoseMoveitAction : Action<PoseMoveitActionGoal, PoseMoveitActionResult, PoseMoveitActionFeedback, PoseMoveitGoal, PoseMoveitResult, PoseMoveitFeedback>
    {
        public const string RosMessageName = "Moveit/PoseMoveitAction";

        public PoseMoveitAction() : base()
        {
            this.action_goal = new PoseMoveitActionGoal();
            this.action_result = new PoseMoveitActionResult();
            this.action_feedback = new PoseMoveitActionFeedback();
        }

    }
}
