/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.FollowObject
{
    public class FollowObjectMoveitGoal : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "FollowObject/FollowObjectMoveitGoal";

        // Goal definition
        public Pose targetPose;

        public FollowObjectMoveitGoal()
        {
            this.targetPose = new Pose();
        }

        public FollowObjectMoveitGoal(Pose targetPose)
        {
            this.targetPose = targetPose;
        }
    }
}
