/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.FollowObject
{
    public class FollowObjectMoveitAction : Action<FollowObjectMoveitActionGoal, FollowObjectMoveitActionResult, FollowObjectMoveitActionFeedback, FollowObjectMoveitGoal, FollowObjectMoveitResult, FollowObjectMoveitFeedback>
    {
        [JsonIgnore]
        public const string RosMessageName = "FollowObject/FollowObjectMoveitAction";

        public FollowObjectMoveitAction() : base()
        {
            this.action_goal = new FollowObjectMoveitActionGoal();
            this.action_result = new FollowObjectMoveitActionResult();
            this.action_feedback = new FollowObjectMoveitActionFeedback();
        }

    }
}
